<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Discussion.aspx.cs" Inherits="Discussion" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Untitled Page</title>
</head>
<body style="background-color: teal; font-family: Times New Roman;">
    <form id="form1" runat="server">
    <div style="background-color: teal; text-align: center;">
        <asp:Button ID="btnmenu" runat="server" BackColor="White" BorderColor="Black" PostBackUrl="~/Menu.aspx"
            Style="z-index: 100; left: 332px; position: absolute; top: 2px" Text="Menu"
            Width="95px" />
        <asp:Button ID="btnhome" runat="server" BackColor="White" BorderColor="Black" PostBackUrl="~/Map.aspx"
            Style="z-index: 101; left: 227px; position: absolute; top: 5px" Text="Home Page"
            Width="94px" />
        &nbsp;&nbsp;<br />
        <asp:Label ID="Label2" runat="server" Font-Size="Smaller" Height="38px" Style="z-index: 102;
            left: 644px; position: absolute; top: 171px" Width="236px"></asp:Label>
        <br />
        <strong><span style="font-size: 48pt; color: white; text-decoration: underline">
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:commentConnectionString %>"
                SelectCommand="SELECT * FROM [com]"></asp:SqlDataSource>
            &nbsp;&nbsp;
            <asp:Label ID="Label3" runat="server" Font-Size="Smaller" Height="1px" Style="z-index: 103;
                left: 636px; position: absolute; top: -62px" Text="WELCOME TO USER PROFILE" Width="1px"></asp:Label>
            <asp:Button ID="btncancel" runat="server" BackColor="White" BorderColor="Black" OnClick="btncancel_Click"
                Style="z-index: 104; left: 95px; position: absolute; top: 604px" Text="Cancel"
                Width="93px" />
            <asp:Button ID="Button1" runat="server" BorderColor="Black" OnClick="Button1_Click"
                Style="z-index: 105; left: 5px; position: absolute; top: 606px" Text="Post" Width="81px" />
            <asp:Image ID="Image1" runat="server" Height="188px" ImageUrl="~/nhm-wildlife-photographer-of-the-year-2007.jpg"
                Style="z-index: 106; left: 275px; position: absolute; top: 52px" Width="317px" />
            <asp:Label ID="Label1" runat="server" Font-Size="Smaller" Height="1px" Style="z-index: 107;
                left: 3px; position: absolute; top: 8px" Text="Do you want to post anything?"
                Width="185px"></asp:Label>
            &nbsp;
            <asp:DataList ID="DataList1" runat="server" DataKeyField="username" DataSourceID="SqlDataSource1"
                Font-Size="Smaller" Height="584px" Style="z-index: 108; left: 416px; position: absolute;
                top: 267px">
                <ItemTemplate>
                    username:
                    <asp:Label ID="usernameLabel" runat="server" Text='<%# Eval("username") %>'></asp:Label><br />
                    comment:
                    <asp:Label ID="commentLabel" runat="server" Text='<%# Eval("comment") %>'></asp:Label><br />
                    <br />
                </ItemTemplate>
            </asp:DataList>
            &nbsp;
            <asp:DetailsView ID="DetailsView1" runat="server" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False"
                DataMember="DefaultView" DataSourceID="SqlDataSource2" Font-Size="Smaller" Height="50px"
                Style="z-index: 110; left: 16px; position: absolute; top: 285px" Width="40px">
                <Fields>
                    <asp:BoundField DataField="username" HeaderText="username" SortExpression="username" />
                    <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:commentConnectionString2 %>"
                SelectCommand="SELECT * FROM [com]"></asp:SqlDataSource>
            <asp:AccessDataSource ID="AccessDataSource1" runat="server"></asp:AccessDataSource>
        </span></strong>
    
    </div>
    </form>
</body>
</html>
